on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install LuaRocks
        # You may pin to the exact commit or the version.
        # uses: leafo/gh-actions-luarocks@218573cd14f9a47b079c9b89349f9b71cb5ee706
        uses: leafo/gh-actions-luarocks@v4.0.0
      - run: busted
